### ISSUE TITLE
Add error messages

### ISSUE THREAD

**Issue by johnnymueller** [jacobgraf/pdfshift#2]
I ran into the same issue as #1 and was able to find a workaround. However, if I exceed my PDFShift API usage (say a PDF is 2MB instead of 1MB) it completely breaks the page and gives a Twig error.

Would it be possible to add some type of error catching? It would be very helpful if I could show an error message to users rather than a broken page.

Thanks!
John

**Comment by jacobgraf** [comment]
Yeah, that sounds logical. I'll work on that and let you know when it's done so you can pull down the update. Thanks!

**Comment by johnnymueller** [comment]
Awesome, thanks!

**Comment by jacobgraf** [comment]
This has been fixed in v1.1.0. Give it an update and let me know how it works. Thanks!
